import type { BucketConfig, BucketKey } from '@/types'

export const BUCKET_CONFIG: Record<BucketKey, BucketConfig> = {
  passive_income: {
    key: 'passive_income',
    label: 'Passive Income',
    shortLabel: 'Passive',
    color: '#6366f1',
    bgColor: 'bg-[#6366f1]',
    lightBg: 'bg-indigo-50',
    borderColor: 'border-indigo-200',
    textColor: 'text-indigo-600',
    description: 'Investments & wealth-building',
    icon: '📈',
  },
  must: {
    key: 'must',
    label: 'Must Expenses',
    shortLabel: 'Must',
    color: '#ef4444',
    bgColor: 'bg-[#ef4444]',
    lightBg: 'bg-red-50',
    borderColor: 'border-red-200',
    textColor: 'text-red-600',
    description: 'Non-negotiables: rent, utilities, gym',
    icon: '🏠',
  },
  desire: {
    key: 'desire',
    label: 'Desire',
    shortLabel: 'Desire',
    color: '#f59e0b',
    bgColor: 'bg-[#f59e0b]',
    lightBg: 'bg-amber-50',
    borderColor: 'border-amber-200',
    textColor: 'text-amber-600',
    description: 'Bigger wants: car fund, gadgets, trips',
    icon: '✨',
  },
  self_pampering: {
    key: 'self_pampering',
    label: 'Self Pampering',
    shortLabel: 'Pampering',
    color: '#ec4899',
    bgColor: 'bg-[#ec4899]',
    lightBg: 'bg-pink-50',
    borderColor: 'border-pink-200',
    textColor: 'text-pink-600',
    description: 'Small treats: coffee, haircut, movies',
    icon: '💆',
  },
  personal_growth: {
    key: 'personal_growth',
    label: 'Personal Growth',
    shortLabel: 'Growth',
    color: '#10b981',
    bgColor: 'bg-[#10b981]',
    lightBg: 'bg-emerald-50',
    borderColor: 'border-emerald-200',
    textColor: 'text-emerald-600',
    description: 'Learning & skill development',
    icon: '🌱',
  },
  make_a_difference: {
    key: 'make_a_difference',
    label: 'Make a Difference',
    shortLabel: 'Give',
    color: '#8b5cf6',
    bgColor: 'bg-[#8b5cf6]',
    lightBg: 'bg-violet-50',
    borderColor: 'border-violet-200',
    textColor: 'text-violet-600',
    description: 'Giving & abundance mindset',
    icon: '🤝',
  },
  buffer: {
    key: 'buffer',
    label: 'Buffer',
    shortLabel: 'Buffer',
    color: '#64748b',
    bgColor: 'bg-[#64748b]',
    lightBg: 'bg-slate-50',
    borderColor: 'border-slate-200',
    textColor: 'text-slate-600',
    description: 'Travel + opportunity fund',
    icon: '🛡️',
  },
}

export const BUCKET_ORDER: BucketKey[] = [
  'must',
  'desire',
  'self_pampering',
  'personal_growth',
  'make_a_difference',
  'passive_income',
]

export const DEFAULT_MONTHLY_INCOME = 10000
